language: node_js	
jobs:
  include:
    - stage: test
      if: type = push
      node_js: 6
    - stage: test
      if: type = push
      node_js: 7
    - stage: test
      if: type = push
      node_js: 8
    - stage: test
      if: type = push
      node_js: 9

