language: node_js	
jobs:
  include:
    - stage: test
      if: type = push
      node_js: 6
    - stage: deploy
      node_js: 7
      script:   
        - |
          if [ "$TRAVIS_PULL_REQUEST" == "false" ] ; then
            chmod +x deploy.sh
            ./deploy.sh
          else
            echo "Not PR merge trigger"
          fi